source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TYPublicSpecs.git'

platform :ios, '9.0'

target 'TYNavigationController_Example' do
  pod 'TYNavigationController', :path => '../'

  target 'TYNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
